export const stitchAssets = {
  homeHero: "/images/stitch/high-res/homeHero.webp",
  homeLounge: "/images/stitch/high-res/homeLounge.webp",
  residenceHero: "/images/stitch/willow-grove-residence-concept.webp",
  corridor: "/images/stitch/high-res/corridor.webp",
  suite: "/images/stitch/high-res/suite.webp",
  social: "/images/stitch/high-res/bookClub.webp",
  dining: "/images/stitch/high-res/dining.webp",
  garden: "/images/stitch/high-res/garden.webp",
  sunroom: "/images/stitch/high-res/sunroom.webp",
  artStudio: "/images/stitch/high-res/artStudio.webp",
  wellnessSuite: "/images/stitch/high-res/wellnessSuite.webp",
  serviceSuite: "/images/stitch/high-res/suite.webp",
  careSupport: "/images/stitch/high-res/careSupport.webp",
  healthMonitoring: "/images/stitch/high-res/healthMonitoring.webp",
  yoga: "/images/stitch/high-res/yoga.webp",
  artActivity: "/images/stitch/high-res/artActivity.webp",
  bookClub: "/images/stitch/high-res/bookClub.webp",
} as const;
