export const stitchAssets = {
  homeHero: "/images/stitch/designer/daily-care.webp",
  homeLounge: "/images/stitch/designer/health-check.webp",
  residenceHero: "/images/stitch/willow-grove-residence-concept.webp",
  corridor: "/images/stitch/designer/shared-suite.webp",
  suite: "/images/stitch/designer/shared-suite.webp",
  social: "/images/stitch/designer/music.webp",
  dining: "/images/stitch/designer/dining.webp",
  garden: "/images/stitch/designer/gardening.webp",
  sunroom: "/images/stitch/designer/board-games.webp",
  artStudio: "/images/stitch/designer/crafts.webp",
  wellnessSuite: "/images/stitch/designer/chair-exercise.webp",
  serviceSuite: "/images/stitch/designer/shared-suite.webp",
  careSupport: "/images/stitch/designer/daily-care.webp",
  healthMonitoring: "/images/stitch/designer/consultation.webp",
  yoga: "/images/stitch/designer/chair-exercise.webp",
  artActivity: "/images/stitch/designer/crafts.webp",
  bookClub: "/images/stitch/designer/board-games.webp",
} as const;
